# Generated by Django 4.1.5 on 2026-07-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('Post_nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('sexe', models.CharField(choices=[('Masculin', 'M'), ('Feminin', 'F')], default='Masculin', max_length=20)),
                ('date_de_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('matricule', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=12)),
                ('fonction', models.CharField(max_length=30)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.ecole')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.quartier')),
            ],
        ),
    ]
