# Generated by Django 4.1.5 on 2026-07-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('grh', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.devise')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies', to='grh.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI (Durée Indéterminée)'), ('CDD', 'CDD (Durée Déterminée)'), ('PRESTATAIRE', 'Prestataire externe'), ('STAGE', 'Stagiaire')], default='CDI', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé')], default='ACTIF', max_length=20)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.devise')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='grh.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé Annuel'), ('MALADIE', 'Congé Maladie'), ('MATERNITE', 'Congé Maternité'), ('SANS_SOLDE', 'Congé Sans Solde'), ('AUTRE', 'Autre')], default='ANNUEL', max_length=30)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='grh.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('CONGE', 'En congé')], default='PRESENT', max_length=20)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='grh.personnel')),
            ],
            options={
                'unique_together': {('personnel', 'date')},
            },
        ),
    ]
