# Generated by Django 4.1.5 on 2026-07-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0003_paie_contrat_conge_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='paie',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], default='ESPECES', max_length=20),
        ),
        migrations.AddField(
            model_name='paie',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
