# Generated by Django 4.1.5 on 2026-07-22 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grh', '0004_paie_mode_paiement_paie_reference_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
    ]
