# Generated by Django 4.1.5 on 2026-07-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_alter_eleve_photo'),
        ('grh', '0005_alter_personnel_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(choices=[('Directeur', 'Directeur'), ('Directeur des études', 'Directeur des études'), ('Préfet', 'Préfet'), ('Enseignant', 'Enseignant'), ('Trésorier', 'Trésorier'), ('Caissier', 'Caissier'), ('Comptable', 'Comptable'), ('Secrétaire', 'Secrétaire'), ('Surveillant', 'Surveillant'), ('Autre', 'Autre')], default='Enseignant', max_length=30),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='personnel',
            unique_together={('ecole', 'matricule')},
        ),
    ]
