# Generated by Django 4.1.5 on 2026-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0006_personnel_matricule_auto_fonction_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(choices=[('Directeur', 'Directeur'), ('Directeur des études', 'Directeur des études'), ('Préfet', 'Préfet'), ('Promoteur', 'Promoteur'), ('Enseignant', 'Enseignant'), ('Trésorier', 'Trésorier'), ('Caissier', 'Caissier'), ('Comptable', 'Comptable'), ('Secrétaire', 'Secrétaire'), ('Surveillant', 'Surveillant'), ('Autre', 'Autre')], default='Enseignant', max_length=30),
        ),
    ]
