# Generated by Django 4.1.5 on 2026-08-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0010_personnel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnel'},
        ),
    ]
