# Generated by Django 4.1.5 on 2026-07-09 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_alter_annee_scolaire_anne_scolaire_alter_cycle_cycle_and_more'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.ecole'),
            preserve_default=False,
        ),
    ]
