# Generated by Django 4.1.5 on 2026-07-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_add_ecole_to_eleve_tuteur'),
        ('utilisateur', '0002_utilisateur_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='eleve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_utilisateur', to='inscription.eleve'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tuteur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_utilisateur', to='inscription.tuteur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('DIRECTEUR', 'Directeur'), ('ENSEIGNANT', 'Enseignant'), ('TRESORIE', 'Trésorier'), ('PARENT', 'Parent'), ('ELEVE', 'Elève'), ('PROFESSEUR', 'Professeur'), ('CAISSIER', 'Caissier')], default='DIRECTEUR', max_length=20),
        ),
    ]
