# Generated by Django 4.1.5 on 2026-07-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_add_ecole_to_eleve_tuteur'),
        ('utilisateur', '0003_utilisateur_eleve_utilisateur_tuteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='ecole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.ecole'),
        ),
    ]
