# Generated by Django 4.1.5 on 2026-07-26 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_classe_titulaire'),
        ('utilisateur', '0005_conversation_messageechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('cible_type', models.CharField(choices=[('PARENT', 'Un parent'), ('CLASSE', 'Toute une classe'), ('SECTION', 'Toute une section'), ('ECOLE', "Toute l'école")], default='ECOLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_envoyees', to=settings.AUTH_USER_MODEL)),
                ('cible_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_direction', to='inscription.classe')),
                ('cible_parent', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_recues_directes', to=settings.AUTH_USER_MODEL)),
                ('cible_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_direction', to='inscription.section')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_direction', to='inscription.ecole')),
            ],
            options={
                'verbose_name': 'Communication direction',
                'verbose_name_plural': 'Communications direction',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='utilisateur.communicationdirection')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture communication',
                'verbose_name_plural': 'Lectures communications',
                'unique_together': {('communication', 'parent')},
            },
        ),
    ]
