# Generated by Django 4.1.5 on 2026-07-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_communication_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlecture',
            options={'verbose_name': 'Destinataire / lecture', 'verbose_name_plural': 'Destinataires / lectures'},
        ),
        migrations.AlterField(
            model_name='communicationlecture',
            name='lu_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
