# Generated by Django 4.1.5 on 2026-08-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_communication_lecture_lu_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Photo de profil'),
        ),
    ]
