# Generated by Django 4.1.5 on 2026-08-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_session_connexion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalacces',
            new_name='utilisateur_utilisa_d540ae_idx',
            old_name='utilisateur_utilisa_idx',
        ),
        migrations.RenameIndex(
            model_name='journalacces',
            new_name='utilisateur_action_e03b2d_idx',
            old_name='utilisateur_action_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionconnexion',
            new_name='utilisateur_utilisa_b35e76_idx',
            old_name='utilisateur_utilisa_ended_idx',
        ),
    ]
