# Generated by Django 4.1.5 on 2026-07-20 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscription', '0002_alter_annee_scolaire_anne_scolaire_alter_cycle_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.ecole')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.section')),
            ],
        ),
    ]
