# Generated by Django 4.1.5 on 2026-07-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_alter_classe_options_alter_classe_unique_together'),
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['section__section', 'libelle'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('ecole', 'section', 'code')},
        ),
    ]
