# Generated by Django 4.1.5 on 2026-07-22 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_add_ecole_to_eleve_tuteur'),
        ('pedagogie', '0002_alter_matiere_options_alter_matiere_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravailCote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_travail', models.CharField(choices=[('DEVOIR', 'Devoir'), ('INTERROGATION', 'Interrogation'), ('EXAMEN', 'Examen'), ('COMPOSITION', 'Composition'), ('TP', 'Travail pratique'), ('AUTRE', 'Autre')], default='DEVOIR', max_length=20)),
                ('titre', models.CharField(blank=True, default='', max_length=150)),
                ('date_travail', models.DateField()),
                ('bareme', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_cotes', to='inscription.annee_scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_cotes', to='inscription.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_cotes', to='inscription.ecole')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_cotes', to='pedagogie.matiere')),
            ],
            options={
                'verbose_name': 'Travail coté',
                'verbose_name_plural': 'Travaux cotés',
                'ordering': ['-date_travail', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NoteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('absent', models.BooleanField(default=False)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_travaux', to='inscription.inscription')),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pedagogie.travailcote')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['inscription__eleve__nom', 'inscription__eleve__prenom'],
                'unique_together': {('travail', 'inscription')},
            },
        ),
    ]
