# Generated by Django 4.1.5 on 2026-07-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0006_personnel_matricule_auto_fonction_choices'),
        ('pedagogie', '0003_travailcote_noteeleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='enserignant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grh.personnel'),
            preserve_default=False,
        ),
    ]
