# Generated by Django 4.1.5 on 2026-07-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0006_personnel_matricule_auto_fonction_choices'),
        ('inscription', '0006_classe_titulaire'),
        ('pedagogie', '0004_matiere_enserignant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarque', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_classes', to='inscription.annee_scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_quotidiennes', to='inscription.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_classes', to='inscription.ecole')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_classes_saisies', to='grh.personnel')),
            ],
            options={
                'verbose_name': 'Présence de classe',
                'verbose_name_plural': 'Présences de classe',
                'ordering': ['-date', 'classe__classe'],
                'unique_together': {('classe', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PresenceEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('EXCUSE', 'Excusé')], default='PRESENT', max_length=20)),
                ('commentaire', models.CharField(blank=True, default='', max_length=200)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_quotidiennes', to='inscription.inscription')),
                ('presence_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pedagogie.presenceclasse')),
            ],
            options={
                'verbose_name': 'Présence élève',
                'verbose_name_plural': 'Présences élèves',
                'ordering': ['inscription__eleve__nom', 'inscription__eleve__prenom'],
                'unique_together': {('presence_classe', 'inscription')},
            },
        ),
    ]
