# Generated by Django 4.1.5 on 2026-07-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_classe_titulaire'),
        ('pedagogie', '0005_presenceclasse_presenceeleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_division', models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], max_length=20)),
                ('numero', models.PositiveSmallIntegerField()),
                ('libelle', models.CharField(max_length=60)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions_bulletin', to='inscription.annee_scolaire')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions_bulletin', to='inscription.cycle')),
            ],
            options={
                'verbose_name': 'Division annee (trimestre/semestre)',
                'verbose_name_plural': 'Divisions annee (trimestres/semestres)',
                'ordering': ['annee_scolaire', 'cycle__cycle', 'numero'],
                'unique_together': {('annee_scolaire', 'cycle', 'type_division', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PeriodeBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Numero sur le bulletin (1 a 6 en trimestriel, 1 a 4 en semestriel).')),
                ('libelle', models.CharField(max_length=60)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_bulletin', to='inscription.annee_scolaire')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_bulletin', to='inscription.cycle')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='pedagogie.divisionannee')),
            ],
            options={
                'verbose_name': 'Periode bulletin',
                'verbose_name_plural': 'Periodes bulletin',
                'ordering': ['annee_scolaire', 'cycle__cycle', 'numero'],
                'unique_together': {('annee_scolaire', 'cycle', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='travailcote',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_cotes', to='pedagogie.periodebulletin', verbose_name='Periode bulletin'),
        ),
    ]
