# Generated by Django 4.1.5 on 2026-07-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0006_division_periode_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='maxima_periode',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Points max TJ par période sur le bulletin. Examen de division = 2 × ce maxima.', max_digits=6),
        ),
        migrations.AddField(
            model_name='travailcote',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour un examen de division.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to='pedagogie.divisionannee', verbose_name='Trimestre / semestre (examen)'),
        ),
        migrations.AddField(
            model_name='travailcote',
            name='role_bulletin',
            field=models.CharField(choices=[('TJ', 'Travaux journaliers (période)'), ('EXAMEN', 'Examen (trimestre / semestre)')], default='TJ', help_text='TJ = note de période ; EXAMEN = examen de trimestre/semestre.', max_length=10, verbose_name='Rôle sur le bulletin'),
        ),
        migrations.AlterField(
            model_name='travailcote',
            name='periode',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour les travaux journaliers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_cotes', to='pedagogie.periodebulletin', verbose_name='Période bulletin (TJ)'),
        ),
    ]
