# Generated by Django 4.1.5 on 2026-07-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_classe_titulaire'),
        ('pedagogie', '0007_bulletin_tj_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total general obtenu')),
                ('total_maxima', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maxima generaux')),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pourcentage')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_eleves', to='inscription.ecole')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin', to='inscription.inscription', verbose_name='Inscription / eleve')),
            ],
            options={
                'verbose_name': 'Bulletin eleve',
                'verbose_name_plural': 'Bulletins eleves',
                'ordering': ['-updated_at'],
            },
        ),
    ]
