# Generated by Django 4.1.5 on 2026-07-28 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_classe_titulaire'),
        ('grh', '0006_personnel_matricule_auto_fonction_choices'),
        ('pedagogie', '0008_bulletin_eleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='enserignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_reference', to='grh.personnel', verbose_name='Enseignant de référence'),
        ),
        migrations.CreateModel(
            name='AffectationEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_matieres', to='inscription.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_enseignement', to='inscription.ecole')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_cours', to='grh.personnel', verbose_name='Professeur du cours')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_classes', to='pedagogie.matiere')),
            ],
            options={
                'verbose_name': 'Affectation enseignant (cours)',
                'verbose_name_plural': 'Affectations enseignants (cours)',
                'ordering': ['classe__classe', 'matiere__libelle'],
                'unique_together': {('classe', 'matiere')},
            },
        ),
    ]
