# Generated by Django 4.1.5 on 2026-07-28 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0006_personnel_matricule_auto_fonction_choices'),
        ('inscription', '0006_classe_titulaire'),
        ('pedagogie', '0009_affectation_enseignement_et_enserignant_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursEnLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publie', models.BooleanField(default=False, help_text='Visible par les élèves de la classe une fois publié.', verbose_name='Publié en ligne')),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_ligne', to='inscription.annee_scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_ligne', to='inscription.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_ligne', to='inscription.ecole')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_ligne', to='grh.personnel', verbose_name='Auteur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_ligne', to='pedagogie.matiere')),
            ],
            options={
                'verbose_name': 'Cours en ligne',
                'verbose_name_plural': 'Cours en ligne',
                'ordering': ['matiere__libelle', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='LeconEnLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True, help_text='Texte du cours (explications, exercices, consignes…).')),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube, Vimeo ou autre (optionnel).', verbose_name='Lien vidéo')),
                ('fichier', models.FileField(blank=True, help_text='PDF, image ou document (optionnel).', null=True, upload_to='cours_en_ligne/%Y/%m/', verbose_name='Fichier joint')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('publie', models.BooleanField(default=True, help_text='Décochez pour garder un brouillon non visible aux élèves.', verbose_name='Leçon visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='pedagogie.coursenligne')),
            ],
            options={
                'verbose_name': 'Leçon en ligne',
                'verbose_name_plural': 'Leçons en ligne',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
