# Generated by Django 4.1.5 on 2026-07-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_classe_titulaire'),
        ('pedagogie', '0010_cours_en_ligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenligne',
            name='competences',
            field=models.CharField(blank=True, help_text='Séparées par des virgules (ex: Fractions, Calcul mental).', max_length=400, verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='coursenligne',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=0, help_text='0 = calcul automatique à partir des leçons.', verbose_name='Durée estimée (min)'),
        ),
        migrations.AddField(
            model_name='coursenligne',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='cours_couvertures/%Y/%m/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='coursenligne',
            name='niveau',
            field=models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], default='DEBUTANT', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='coursenligne',
            name='objectifs',
            field=models.TextField(blank=True, help_text='Un objectif par ligne.', verbose_name='Ce que vous allez apprendre'),
        ),
        migrations.AddField(
            model_name='coursenligne',
            name='prerequis',
            field=models.TextField(blank=True, help_text='Ce que l’élève doit déjà savoir.', verbose_name='Prérequis'),
        ),
        migrations.AddField(
            model_name='coursenligne',
            name='public_cible',
            field=models.CharField(blank=True, help_text='Ex: Élèves de 5e année primaire', max_length=200, verbose_name='Public cible'),
        ),
        migrations.AddField(
            model_name='coursenligne',
            name='sous_titre',
            field=models.CharField(blank=True, help_text='Phrase d’accroche visible sous le titre (style LinkedIn Learning).', max_length=300, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='leconenligne',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='Durée (min)'),
        ),
        migrations.AddField(
            model_name='leconenligne',
            name='resume',
            field=models.CharField(blank=True, help_text='Courte description affichée dans le programme du cours.', max_length=300, verbose_name='Résumé'),
        ),
        migrations.AddField(
            model_name='leconenligne',
            name='type_contenu',
            field=models.CharField(choices=[('VIDEO', 'Vidéo'), ('LECTURE', 'Lecture'), ('DOCUMENT', 'Document'), ('EXERCICE', 'Exercice')], default='LECTURE', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='coursenligne',
            name='description',
            field=models.TextField(blank=True, help_text='Présentation détaillée du cours.', verbose_name='À propos du cours'),
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vue', models.BooleanField(default=True)),
                ('terminee', models.BooleanField(default=False)),
                ('vue_at', models.DateTimeField(auto_now_add=True)),
                ('terminee_at', models.DateTimeField(blank=True, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecons', to='inscription.inscription')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='pedagogie.leconenligne')),
            ],
            options={
                'verbose_name': 'Progression leçon',
                'verbose_name_plural': 'Progressions leçons',
                'unique_together': {('inscription', 'lecon')},
            },
        ),
    ]
