# Generated by Django 4.1.5 on 2026-07-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0011_elearning_linkedin_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leconenligne',
            options={'ordering': ['ordre', 'id'], 'verbose_name': 'Sous-chapitre / leçon', 'verbose_name_plural': 'Sous-chapitres / leçons'},
        ),
        migrations.AddField(
            model_name='leconenligne',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cours_sous_chapitres/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='leconenligne',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='pedagogie.coursenligne'),
        ),
        migrations.AlterField(
            model_name='leconenligne',
            name='fichier',
            field=models.FileField(blank=True, help_text='PDF ou document (optionnel).', null=True, upload_to='cours_en_ligne/%Y/%m/', verbose_name='Fichier joint'),
        ),
        migrations.AlterField(
            model_name='leconenligne',
            name='publie',
            field=models.BooleanField(default=True, help_text='Décochez pour garder un brouillon non visible aux élèves.', verbose_name='Sous-chapitre visible'),
        ),
        migrations.CreateModel(
            name='ChapitreCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('resume', models.CharField(blank=True, max_length=300, verbose_name='Résumé')),
                ('contenu', models.TextField(blank=True, help_text='Texte d’introduction du chapitre (optionnel).', verbose_name='Introduction du chapitre')),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube / Vimeo pour ce chapitre.', verbose_name='Vidéo du chapitre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cours_chapitres/%Y/%m/', verbose_name='Image du chapitre')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('publie', models.BooleanField(default=True, verbose_name='Chapitre visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='pedagogie.coursenligne')),
            ],
            options={
                'verbose_name': 'Chapitre de cours',
                'verbose_name_plural': 'Chapitres de cours',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='leconenligne',
            name='chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_chapitres', to='pedagogie.chapitrecours', verbose_name='Chapitre'),
        ),
    ]
