# Generated by Django 4.1.5 on 2026-08-09 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0010_alter_eleve_nationalite'),
        ('grh', '0006_personnel_matricule_auto_fonction_choices'),
        ('pedagogie', '0014_est_encours_periodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursEnDirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Sujets abordés, préparations requises, etc.', verbose_name='Description du cours')),
                ('date_heure_prevue', models.DateTimeField(verbose_name='Date et heure prévues')),
                ('duree_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée estimée (min)')),
                ('jitsi_room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID de salle Jitsi')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_direct', to='inscription.annee_scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_direct', to='inscription.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_direct', to='inscription.ecole')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_direct', to='grh.personnel', verbose_name='Enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_en_direct', to='pedagogie.matiere')),
            ],
            options={
                'verbose_name': 'Cours en direct',
                'verbose_name_plural': 'Cours en direct',
                'ordering': ['-date_heure_prevue'],
            },
        ),
    ]
