# Generated by Django 4.1.5 on 2026-08-09 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedagogie', '0015_coursendirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCoursDirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(blank=True, max_length=150)),
                ('texte', models.TextField(max_length=1000, verbose_name='Question')),
                ('reponse', models.TextField(blank=True, verbose_name='Réponse')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('REPONDUE', 'Répondue')], default='OUVERTE', max_length=20)),
                ('epinglee', models.BooleanField(default=False, verbose_name='Épinglée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repondu_at', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_cours_direct', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pedagogie.coursendirect')),
            ],
            options={
                'verbose_name': 'Question de cours en direct',
                'verbose_name_plural': 'Questions de cours en direct',
                'ordering': ['-epinglee', '-created_at'],
            },
        ),
    ]
