# Generated by Django 4.1.5 on 2026-08-12 23:55

from django.db import migrations, models
import pedagogie.storage
import pedagogie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0016_question_cours_direct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitrecours',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='leconenligne',
            name='video_url',
        ),
        migrations.AddField(
            model_name='chapitrecours',
            name='video',
            field=models.FileField(blank=True, help_text='Fichier vidéo hébergé (MP4/WebM recommandés).', null=True, storage=pedagogie.storage.get_cours_video_storage, upload_to=pedagogie.storage.upload_to_cours_video, validators=[pedagogie.validators.validate_cours_video], verbose_name='Vidéo du chapitre'),
        ),
        migrations.AddField(
            model_name='leconenligne',
            name='video',
            field=models.FileField(blank=True, help_text='Fichier vidéo hébergé (MP4/WebM recommandés).', null=True, storage=pedagogie.storage.get_cours_video_storage, upload_to=pedagogie.storage.upload_to_cours_video, validators=[pedagogie.validators.validate_cours_video], verbose_name='Vidéo'),
        ),
    ]
