# Generated by Django 4.1.5 on 2026-08-18 21:48

from django.db import migrations, models
import django.db.models.deletion
import pedagogie.storage
import pedagogie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_eleve_sexe_sans_defaut'),
        ('grh', '0011_edt_et_mobile_money'),
        ('pedagogie', '0017_cours_video_fichier_cloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitrecours',
            name='video',
            field=models.FileField(blank=True, help_text='Fichier vidéo hébergé (MP4/WebM). Taille max. configurable (COURS_VIDEO_MAX_MB).', null=True, storage=pedagogie.storage.get_cours_video_storage, upload_to=pedagogie.storage.upload_to_cours_video, validators=[pedagogie.validators.validate_cours_video], verbose_name='Vidéo du chapitre'),
        ),
        migrations.AlterField(
            model_name='leconenligne',
            name='video',
            field=models.FileField(blank=True, help_text='Fichier vidéo hébergé (MP4/WebM). Taille max. configurable (COURS_VIDEO_MAX_MB).', null=True, storage=pedagogie.storage.get_cours_video_storage, upload_to=pedagogie.storage.upload_to_cours_video, validators=[pedagogie.validators.validate_cours_video], verbose_name='Vidéo'),
        ),
        migrations.CreateModel(
            name='CreneauEmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=40)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_edt', to='inscription.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_edt', to='inscription.ecole')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_edt', to='grh.personnel')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_edt', to='pedagogie.matiere')),
            ],
            options={
                'verbose_name': "Créneau d'emploi du temps",
                'verbose_name_plural': "Créneaux d'emploi du temps",
                'ordering': ['classe', 'jour', 'heure_debut'],
            },
        ),
    ]
