# Generated by Django 4.1.5 on 2026-08-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0020_ressource_partagee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursenligne',
            name='publie',
            field=models.BooleanField(default=False, help_text='Visible par les élèves des classes sélectionnées une fois publié.', verbose_name='Publié en ligne'),
        ),
    ]
