# Generated by Django 4.1.5 on 2026-07-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_Scolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anne_scolaire', models.CharField(max_length=9)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_encoure', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=10)),
                ('capacite_max', models.IntegerField()),
                ('salle', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('HUMANITE', 'Humanite')], default='Primaire', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=250)),
                ('Post_nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('sexe', models.CharField(choices=[('Masculin', 'M'), ('Feminin', 'F')], default='Masculin', max_length=20)),
                ('date_de_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=250)),
                ('Post_nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('lien_parente', models.CharField(choices=[('PERE', 'Pére'), ('MERE', 'Mère'), ('TITEUR', 'Titeur'), ('AUTRE', 'Autre')], default='pere', max_length=25)),
                ('telephone', models.CharField(max_length=14)),
                ('telephone2', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ins', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('type_iscription', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('REINSCRIPTION', 'Reinscription'), ('TRANSFERT', 'Transfert')], default='NOUVELLE', max_length=20)),
                ('frais_inscription', models.BooleanField(default=False)),
                ('annee_s', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.annee_scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.eleve')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.quartier'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='titeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.tuteur'),
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ecole', models.CharField(max_length=20)),
                ('ecole', models.CharField(max_length=150)),
                ('type_ecole', models.CharField(choices=[('PUBLICQUE', 'Publique'), ('PRIVEE', 'Privée'), ('CONVENTIONNEE', 'Conventionnée')], default='PRIVEE', max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone1', models.CharField(max_length=15)),
                ('telephone2', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('activation', models.BooleanField(default=False)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.quartier')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.ecole'),
        ),
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.section'),
        ),
        migrations.AddField(
            model_name='annee_scolaire',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.ecole'),
        ),
    ]
