# Generated by Django 4.1.5 on 2026-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee_scolaire',
            name='anne_scolaire',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='cycle',
            field=models.CharField(choices=[('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('HUMANITE', 'Humanite')], default='Primaire', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
