# Generated by Django 4.1.5 on 2026-07-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_alter_annee_scolaire_anne_scolaire_alter_cycle_cycle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('ecole', 'section', 'classe')},
        ),
    ]
