# Generated by Django 4.1.5 on 2026-07-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_add_ecole_to_eleve_tuteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
