# Generated by Django 4.1.5 on 2026-07-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0006_personnel_matricule_auto_fonction_choices'),
        ('inscription', '0005_alter_eleve_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='titulaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_titulaires', to='grh.personnel', verbose_name='Enseignant titulaire'),
        ),
    ]
