# Generated by Django 4.1.5 on 2026-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_annee_scolaire_nationale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuteur',
            name='telephone2',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
