# Generated by Django 4.1.5 on 2026-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_residence_tuteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='nationalite',
            field=models.CharField(default='Congolaise', max_length=50),
        ),
    ]
