# Generated by Django 4.1.5 on 2026-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0011_eleve_matricule_unique_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'M'), ('Feminin', 'F')], max_length=20),
        ),
    ]
