# Generated by Django 4.1.5 on 2026-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_eleve_sexe_sans_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuteur',
            name='Post_nom',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tuteur',
            name='prenom',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
