# Generated by Django 4.1.5 on 2026-07-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(default='USD', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Frais_Scolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('echeance', models.DateField()),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.annee_scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.classe')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.devise')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inscription.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=16)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mode_paiement', models.CharField(choices=[(' ESPECES', ' ESPECE'), ('MOBILE_MONEY', 'MOBILE_MONEY'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE')], default='ESPECE', max_length=12)),
                ('reference_trans', models.CharField(max_length=25, null=True)),
                ('date_encodage', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.CharField(max_length=30)),
                ('statut', models.CharField(choices=[(' VALIDE', ' VALIDE'), ('ANNULE', 'ANNULE'), ('EN_ATTENTE', 'EN_ATTENTE')], default='EN_ATTENTE', max_length=20)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.devise')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.inscription')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.frais_scolaire')),
            ],
        ),
        migrations.AddField(
            model_name='frais_scolaire',
            name='type_frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.typefrais'),
        ),
    ]
