# Generated by Django 4.1.5 on 2026-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='devise',
            field=models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'ESPECE'), ('MOBILE_MONEY', 'MOBILE_MONEY'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE')], default='ESPECES', max_length=12),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'VALIDE'), ('ANNULE', 'ANNULE'), ('EN_ATTENTE', 'EN_ATTENTE')], default='EN_ATTENTE', max_length=20),
        ),
    ]
