# Generated by Django 4.1.5 on 2026-07-09 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_devise_devise_alter_paiement_mode_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.devise')),
            ],
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecriture', models.DateField()),
                ('libelle', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PieceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('date', models.DateField()),
                ('libelle', models.CharField(blank=True, default='', max_length=255)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.journalcomptable')),
            ],
        ),
        migrations.CreateModel(
            name='EcritureLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=6)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finances.ecriture')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écritures",
            },
        ),
        migrations.AddField(
            model_name='ecriture',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.journalcomptable'),
        ),
        migrations.AddField(
            model_name='ecriture',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.piececomptable'),
        ),
    ]
