# Generated by Django 4.1.5 on 2026-07-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_alter_annee_scolaire_anne_scolaire_alter_cycle_cycle_and_more'),
        ('finances', '0003_comptecomptable_ecriture_journalcomptable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptecomptable',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='ecriture',
            options={'ordering': ['-date_ecriture', 'id']},
        ),
        migrations.AlterModelOptions(
            name='journalcomptable',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='piececomptable',
            options={'ordering': ['-date', 'reference']},
        ),
        migrations.AddField(
            model_name='comptecomptable',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription.ecole'),
        ),
        migrations.AddField(
            model_name='ecriture',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription.ecole'),
        ),
        migrations.AddField(
            model_name='journalcomptable',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription.ecole'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription.ecole'),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='journalcomptable',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='piececomptable',
            name='reference',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='comptecomptable',
            unique_together={('ecole', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='journalcomptable',
            unique_together={('ecole', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='piececomptable',
            unique_together={('ecole', 'reference')},
        ),
    ]
