# Generated by Django 4.1.5 on 2026-07-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_add_ecole_to_eleve_tuteur'),
        ('finances', '0004_alter_comptecomptable_options_alter_ecriture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frais_scolaire',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.section'),
        ),
    ]
