# Generated by Django 4.1.5 on 2026-07-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_frais_scolaire_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frais_scolaire',
            old_name='classe',
            new_name='section',
        ),
    ]
