# Generated by Django 4.1.5 on 2026-08-07 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_annee_scolaire_nationale'),
        ('finances', '0006_rename_classe_frais_scolaire_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='devise_origine',
            field=models.ForeignKey(blank=True, help_text='Devise réellement encaissée (si différente du frais)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_origine', to='finances.devise'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_origine',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant réellement reçu avant conversion', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='taux_change',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux appliqué : CDF pour 1 USD', max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.DecimalField(decimal_places=4, help_text='Nombre de CDF pour 1 USD', max_digits=18)),
                ('date_effet', models.DateField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('saisi_par', models.CharField(blank=True, max_length=80)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_change', to='inscription.ecole')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['-date_effet', '-date_saisie'],
            },
        ),
    ]
