# Generated by Django 4.1.5 on 2026-08-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_taux_change_and_paiement_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeModificationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('demande_par', models.CharField(max_length=80)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITEE', 'Traitée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('traite_par', models.CharField(blank=True, max_length=80)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('reponse_admin', models.TextField(blank=True, verbose_name="Réponse de l'admin")),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modification', to='finances.paiement')),
            ],
            options={
                'verbose_name': 'Demande de modification de paiement',
                'verbose_name_plural': 'Demandes de modification de paiement',
                'ordering': ['-date_demande'],
            },
        ),
    ]
