# Generated by Django 4.1.5 on 2026-08-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_annee_scolaire_nationale'),
        ('finances', '0008_demande_modification_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('IGNORE', 'Ignoré')], default='ENVOYE', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('reponse_api', models.TextField(blank=True)),
                ('erreur', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_whatsapp', to='inscription.ecole')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_whatsapp', to='finances.paiement')),
            ],
            options={
                'verbose_name': 'Notification WhatsApp',
                'verbose_name_plural': 'Notifications WhatsApp',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ConfigWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('ULTRAMSG', 'Ultramsg'), ('META', 'Meta Cloud API (WhatsApp Business)'), ('LOG', 'Mode test (journal uniquement)')], default='ULTRAMSG', max_length=20)),
                ('api_token', models.CharField(blank=True, help_text='Token Ultramsg / Access token Meta', max_length=255)),
                ('instance_id', models.CharField(blank=True, help_text='Instance ID Ultramsg ou Phone Number ID Meta', max_length=80)),
                ('api_url', models.CharField(blank=True, help_text='URL API optionnelle (sinon URL par défaut du fournisseur)', max_length=255)),
                ('indicatif_pays', models.CharField(default='243', help_text='Indicatif sans + (ex. 243 pour la RDC)', max_length=5)),
                ('template_meta', models.CharField(blank=True, help_text='Nom du modèle Meta (si messages texte libres refusés)', max_length=100)),
                ('message_modele', models.TextField(blank=True, help_text='Placeholders : {parent} {eleve} {classe} {ecole} {numero_recu} {frais} {montant} {devise} {mode} {date}')),
                ('ecole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_whatsapp', to='inscription.ecole')),
            ],
            options={
                'verbose_name': 'Configuration WhatsApp',
                'verbose_name_plural': 'Configurations WhatsApp',
            },
        ),
    ]
