# Generated by Django 4.1.5 on 2026-08-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_whatsapp_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='configwhatsapp',
            name='template_langue',
            field=models.CharField(blank=True, default='fr', help_text='Code langue du modèle Meta (ex. fr, fr_FR, en)', max_length=10),
        ),
        migrations.AddField(
            model_name='configwhatsapp',
            name='template_variables',
            field=models.CharField(blank=True, default='eleve,montant_affiche,numero_recu,frais,classe,date', help_text="Clés séparées par des virgules, dans l'ordre des {{1}}, {{2}}, … Ex. eleve,montant_affiche,numero_recu,frais,classe,date", max_length=255),
        ),
        migrations.AlterField(
            model_name='configwhatsapp',
            name='message_modele',
            field=models.TextField(blank=True, help_text='Placeholders (Ultramsg / mode texte) : {parent} {eleve} {classe} {ecole} {numero_recu} {frais} {montant} {devise} {montant_affiche} {mode} {date}'),
        ),
        migrations.AlterField(
            model_name='configwhatsapp',
            name='template_meta',
            field=models.CharField(blank=True, help_text='Nom du modèle Meta approuvé (ex. recu_paiement_ecole)', max_length=100),
        ),
    ]
