# Generated by Django 4.1.5 on 2026-08-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_whatsapp_config_centrale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configwhatsapp',
            name='api_token',
            field=models.TextField(blank=True, help_text='Token Ultramsg / Access token Meta (jeton permanent, souvent > 255 caractères)'),
        ),
    ]
