# Generated by Django 4.1.5 on 2026-08-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0011_eleve_matricule_unique_global'),
        ('finances', '0013_whatsapp_token_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_journee', models.DateField(verbose_name='Journée')),
                ('caissier', models.CharField(max_length=80)),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('nb_paiements', models.PositiveIntegerField(default=0)),
                ('nb_eleves', models.PositiveIntegerField(default=0)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_especes_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_especes_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_mobile_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_mobile_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_autres_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_autres_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures_caisse', to='inscription.ecole')),
            ],
            options={
                'verbose_name': 'Clôture de caisse',
                'verbose_name_plural': 'Clôtures de caisse',
                'ordering': ['-date_journee', '-date_cloture'],
            },
        ),
        migrations.AddConstraint(
            model_name='cloturecaisse',
            constraint=models.UniqueConstraint(fields=('ecole', 'date_journee', 'caissier'), name='uniq_cloture_caisse_ecole_jour_caissier'),
        ),
    ]
