# Generated by Django 4.1.5 on 2026-08-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_eleve_sexe_sans_defaut'),
        ('finances', '0014_cloture_caisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fixation', models.DateTimeField()),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('fixe_par', models.CharField(blank=True, max_length=80)),
                ('commentaire', models.TextField(blank=True)),
                ('capacite_totale', models.PositiveIntegerField(default=0)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='inscription.annee_scolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets_annuels', to='inscription.ecole')),
            ],
            options={
                'verbose_name': 'Budget annuel',
                'verbose_name_plural': 'Budgets annuels',
                'ordering': ['-annee__anne_scolaire', '-date_fixation'],
            },
        ),
        migrations.CreateModel(
            name='LigneBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('montant_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('type_frais_libelle', models.CharField(blank=True, max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finances.budgetannuel')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budget', to='inscription.classe')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.devise')),
            ],
            options={
                'verbose_name': 'Ligne de budget',
                'verbose_name_plural': 'Lignes de budget',
                'ordering': ['classe__section__section', 'classe__classe'],
            },
        ),
        migrations.AddConstraint(
            model_name='lignebudget',
            constraint=models.UniqueConstraint(fields=('budget', 'classe'), name='uniq_ligne_budget_classe'),
        ),
        migrations.AddConstraint(
            model_name='budgetannuel',
            constraint=models.UniqueConstraint(fields=('ecole', 'annee'), name='uniq_budget_ecole_annee'),
        ),
    ]
