# Generated by Django 4.1.5 on 2026-08-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_eleve_sexe_sans_defaut'),
        ('finances', '0017_whatsapp_provider_bird'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentionPaiementMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('telephone', models.CharField(max_length=20)),
                ('provider', models.CharField(choices=[('AIRTEL', 'Airtel Money'), ('ORANGE', 'Orange Money'), ('MPESA', 'M-Pesa'), ('FLEXPAIE', 'FlexPaie'), ('AUTRE', 'Autre')], default='AIRTEL', max_length=20)),
                ('statut', models.CharField(choices=[('INITIEE', 'Initiée'), ('EN_ATTENTE', 'En attente opérateur'), ('PAYEE', 'Payée'), ('ECHEC', 'Échec'), ('EXPIREE', 'Expirée')], default='INITIEE', max_length=20)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('reference_operateur', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.devise')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentions_mobile', to='inscription.ecole')),
                ('frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentions_mobile', to='finances.frais_scolaire')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentions_mobile', to='inscription.inscription')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentions_mobile', to='finances.paiement')),
            ],
            options={
                'verbose_name': 'Intention de paiement mobile',
                'verbose_name_plural': 'Intentions de paiement mobile',
                'ordering': ['-created_at'],
            },
        ),
    ]
