# Generated by Django 4.1.5 on 2026-08-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_whatsapp_langue_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configwhatsapp',
            name='template_langue',
            field=models.CharField(blank=True, default='fr_FR', help_text='Code langue Meta (fr ou fr_FR)', max_length=10),
        ),
        migrations.AlterField(
            model_name='configwhatsapp',
            name='template_meta',
            field=models.CharField(blank=True, help_text='Modèle Meta reçu de paiement (ex. recu_de_paiement) ou slug Bird', max_length=100),
        ),
    ]
