# Generated by Django 4.1.5 on 2026-08-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0022_alter_configwhatsapp_template_langue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configwhatsapp',
            name='meta_app_secret',
            field=models.TextField(blank=True, help_text="App Secret Meta (si « Require App Secret » est activé sur l'app). Sinon WHATSAPP_META_APP_SECRET dans .env."),
        ),
    ]
