# Generated by Django 4.1.5 on 2026-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_whatsapp_meta_app_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frais_scolaire',
            options={'ordering': ['niveau_priorite', 'echeance', 'id'], 'verbose_name': 'Frais scolaire', 'verbose_name_plural': 'Frais scolaires'},
        ),
        migrations.AddField(
            model_name='frais_scolaire',
            name='niveau_priorite',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Ordre de priorité de paiement (1 = priorité maximale / à payer en premier, 2 = niveau suivant, etc.).', verbose_name='Niveau de priorité'),
        ),
    ]
