"""
Django settings for ds project.

Generated by 'django-admin startproject' using Django 4.1.5.
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """Charge un fichier .env simple (sans dépendance externe)."""
    if not path.is_file():
        return
    try:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key:
                os.environ.setdefault(key, value)
    except OSError:
        pass


_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


def _env_flag(name, default="0"):
    return os.environ.get(name, default) in ("1", "true", "True", "yes")


_INSECURE_SECRET_KEY = (
    "django-insecure--i%o)bf$!28(2-517==ms)-sx_j691go=k&awswzvl@^*t#@n)"
)
_PLACEHOLDER_SECRETS = frozenset(
    {
        _INSECURE_SECRET_KEY,
        "changez-moi-en-production",
    }
)

_secret_from_env = (os.environ.get("DJANGO_SECRET_KEY") or "").strip()
if _secret_from_env:
    SECRET_KEY = _secret_from_env
elif _env_flag("DJANGO_DEBUG", "0"):
    # Dev uniquement : clé locale non utilisée en production.
    SECRET_KEY = _INSECURE_SECRET_KEY
else:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY doit être défini (variable d'environnement)."
    )

# Défaut production (DEBUG off). En local : copier .env.example (DJANGO_DEBUG=1).
DEBUG = _env_flag("DJANGO_DEBUG", "0")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
]
# Dev / Quick Tunnel Cloudflare (*.trycloudflare.com)
if DEBUG:
    _dev_hosts = ["localhost", "127.0.0.1", "[::1]", ".trycloudflare.com"]
    for h in _dev_hosts:
        if h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(h)
    CSRF_TRUSTED_ORIGINS = [
        o.strip()
        for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
        if o.strip()
    ] or [
        "https://*.trycloudflare.com",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
    # cloudflared envoie X-Forwarded-Proto=https
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Cookies / en-têtes — toujours (dev + prod)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
# Fermeture après 15 min d'inactivité (cookie + sessions de connexion).
SESSION_IDLE_SECONDS = int(os.environ.get("SESSION_IDLE_SECONDS", "900"))
SESSION_COOKIE_AGE = SESSION_IDLE_SECONDS
SESSION_SAVE_EVERY_REQUEST = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# Mot de passe : Argon2 si disponible, sinon PBKDF2 (comptes existants inchangés).
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]
try:
    import argon2  # noqa: F401
    PASSWORD_HASHERS.insert(0, "django.contrib.auth.hashers.Argon2PasswordHasher")
except ImportError:
    pass

# Lien de réinitialisation : 60 minutes (jeton à usage unique côté Django).
PASSWORD_RESET_TIMEOUT = int(os.environ.get("PASSWORD_RESET_TIMEOUT", "3600"))

# Verrouillage connexion / codes OTP
LOGIN_LOCKOUT_LIMIT = int(os.environ.get("LOGIN_LOCKOUT_LIMIT", "5"))
LOGIN_LOCKOUT_MINUTES = int(os.environ.get("LOGIN_LOCKOUT_MINUTES", "15"))
OTP_TTL_MINUTES = int(os.environ.get("OTP_TTL_MINUTES", "10"))
OTP_MAX_ATTEMPTS = int(os.environ.get("OTP_MAX_ATTEMPTS", "5"))
OTP_RENVOI_COOLDOWN_SECONDS = int(os.environ.get("OTP_RENVOI_COOLDOWN_SECONDS", "60"))
OTP_RENVOI_MAX = int(os.environ.get("OTP_RENVOI_MAX", "5"))
# 2FA WhatsApp à la connexion (MFA_WHATSAPP=1 dans .env).
MFA_WHATSAPP_ACTIF = _env_flag("MFA_WHATSAPP", "0")
# Code WhatsApp à l'inscription (INSCRIPTION_WHATSAPP=1 dans .env).
INSCRIPTION_WHATSAPP_ACTIF = _env_flag("INSCRIPTION_WHATSAPP", "0")
AUDIT_VOLUME_SEUIL = int(os.environ.get("AUDIT_VOLUME_SEUIL", "40"))
AUDIT_VOLUME_MINUTES = int(os.environ.get("AUDIT_VOLUME_MINUTES", "10"))

# HTTPS / cookies Secure / HSTS — production uniquement (OVH derrière reverse proxy)
if not DEBUG:
    if (
        SECRET_KEY in _PLACEHOLDER_SECRETS
        or SECRET_KEY.startswith("django-insecure-")
        or len(SECRET_KEY) < 50
    ):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY doit être défini en production "
            "(≥ 50 caractères aléatoires, pas la valeur d'exemple)."
        )
    if not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS doit lister le(s) domaine(s) de production "
            "(sans « * »)."
        )
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = _env_flag("SECURE_HSTS_PRELOAD", "1")
    CSRF_TRUSTED_ORIGINS = [
        o.strip()
        for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
        if o.strip()
    ]
    if not CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = [
            f"https://{h}"
            for h in ALLOWED_HOSTS
            if h and h not in ("*", ".localhost")
        ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inscription',
    'grh',
    'finances',
    'utilisateur',
    'pedagogie.apps.PedagogieConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'utilisateur.middleware.SessionConnexionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utilisateur.middleware.SecurityHeadersMiddleware',
    'utilisateur.middleware.RestrictionPortailMiddleware',
]

ROOT_URLCONF = 'ds.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ds.breadcrumbs.breadcrumbs',
                'utilisateur.context_processors.portail_enseignant',
            ],
        },
    },
]

WSGI_APPLICATION = 'ds.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

def _database_from_url(url: str) -> dict:
    """Parse DATABASE_URL (Coolify / PaaS) vers le dict Django."""
    from urllib.parse import unquote, urlparse

    parsed = urlparse(url)
    scheme = (parsed.scheme or "mysql").split("+")[0]
    engines = {
        "mysql": "django.db.backends.mysql",
        "mariadb": "django.db.backends.mysql",
        "postgres": "django.db.backends.postgresql",
        "postgresql": "django.db.backends.postgresql",
        "sqlite": "django.db.backends.sqlite3",
    }
    return {
        "ENGINE": engines.get(scheme, "django.db.backends.mysql"),
        "NAME": unquote((parsed.path or "/").lstrip("/") or "digital_school"),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "127.0.0.1",
        "PORT": str(parsed.port or (3306 if scheme in ("mysql", "mariadb") else 5432)),
    }


if os.environ.get("DATABASE_URL"):
    DATABASES = {"default": _database_from_url(os.environ["DATABASE_URL"])}
else:
    DATABASES = {
        "default": {
            "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.mysql"),
            "NAME": os.environ.get("DB_NAME", "digital_school"),
            "USER": os.environ.get("DB_USER", "root"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "3306"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# Dossier de fichiers statiques globaux (partagés entre toutes les applications)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Dossier de destination pour collectstatic (production / Coolify)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL='utilisateur.Utilisateur'

LOGIN_URL = 'utilisateur:login'
LOGIN_REDIRECT_URL = 'utilisateur:post_login'
LOGOUT_REDIRECT_URL = 'utilisateur:login'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Vidéos de cours hors /media/ public (nginx ne les sert pas).
PRIVATE_MEDIA_ROOT = Path(
    os.environ.get('PRIVATE_MEDIA_ROOT', str(BASE_DIR / 'private_media'))
)

# ---------------------------------------------------------------------------
# Vidéos de cours — stockage local (dev) ou S3-compatible (Cloudflare R2, B2…)
# Coupe YouTube : fichiers hébergés sous contrôle de l'école.
# ---------------------------------------------------------------------------
COURS_VIDEO_MAX_MB = int(os.environ.get('COURS_VIDEO_MAX_MB', '70'))
COURS_VIDEO_LOCATION = os.environ.get('COURS_VIDEO_LOCATION', 'cours_videos')
RESSOURCE_FICHIER_MAX_MB = int(os.environ.get('RESSOURCE_FICHIER_MAX_MB', '25'))
# Limite upload HTTP (alignée sur la taille max vidéo + marge)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', str(COURS_VIDEO_MAX_MB * 1024 * 1024))
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE', str(10 * 1024 * 1024))
)

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '') or None
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')
AWS_S3_SIGNATURE_VERSION = os.environ.get('AWS_S3_SIGNATURE_VERSION', 's3v4')
AWS_S3_ADDRESSING_STYLE = os.environ.get('AWS_S3_ADDRESSING_STYLE', 'path')
AWS_DEFAULT_ACL = 'private'
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = int(os.environ.get('AWS_QUERYSTRING_EXPIRE', '3600'))
AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
# Domaine CDN optionnel (ex. vidéos.votredomaine.com sur R2)
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '') or None

# WhatsApp — notifications (valeurs par défaut ; config centrale en BDD)
WHATSAPP_TIMEOUT = int(os.environ.get('WHATSAPP_TIMEOUT', '20'))
WHATSAPP_META_API_VERSION = os.environ.get('WHATSAPP_META_API_VERSION', 'v19.0')
# Noms des modèles Meta approuvés (surchargeables en BDD)
WHATSAPP_META_TEMPLATE_PAIEMENT = (
    os.environ.get("WHATSAPP_META_TEMPLATE_PAIEMENT", "recu_de_paiement").strip()
    or "recu_de_paiement"
)
WHATSAPP_META_TEMPLATE_RELANCE = (
    os.environ.get("WHATSAPP_META_TEMPLATE_RELANCE", "relance_minerval").strip()
    or "relance_minerval"
)
WHATSAPP_META_TEMPLATE_ANNONCE = (
    os.environ.get("WHATSAPP_META_TEMPLATE_ANNONCE", "annonce_ecole").strip()
    or "annonce_ecole"
)
WHATSAPP_META_TEMPLATE_OTP = (
    os.environ.get("WHATSAPP_META_TEMPLATE_OTP", "code_verification").strip()
    or "code_verification"
)
WHATSAPP_META_LANGUAGE = (
    os.environ.get("WHATSAPP_META_LANGUAGE", "fr").strip() or "fr"
)

# Visioconférence Jitsi / JaaS (cours en direct)
JITSI_PROVIDER = os.environ.get('JITSI_PROVIDER', 'public').strip().lower()
JITSI_DOMAIN = os.environ.get(
    'JITSI_DOMAIN',
    '8x8.vc' if JITSI_PROVIDER == 'jaas' else 'meet.jit.si',
)
JITSI_ROOM_PREFIX = os.environ.get('JITSI_ROOM_PREFIX', 'ds')
JITSI_JAAS_APP_ID = os.environ.get('JITSI_JAAS_APP_ID', '').strip()
JITSI_JAAS_API_KEY = os.environ.get('JITSI_JAAS_API_KEY', '').strip()
JITSI_JAAS_PRIVATE_KEY = os.environ.get('JITSI_JAAS_PRIVATE_KEY', '').strip()
JITSI_JAAS_JWT_TTL_SECONDS = int(os.environ.get('JITSI_JAAS_JWT_TTL_SECONDS', '3600'))

# E-mail (optionnel, hors authentification).
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_flag('EMAIL_USE_TLS', '1')
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Digital School <noreply@digitalschool.local>",
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Proxys de confiance (X-Forwarded-For uniquement si REMOTE_ADDR est dans cette liste).
TRUSTED_PROXIES = tuple(
    p.strip()
    for p in os.environ.get("TRUSTED_PROXIES", "127.0.0.1,::1").split(",")
    if p.strip()
)

# Mobile Money — webhook opérateur (laisser vide = webhook refusé).
MOBILE_MONEY_WEBHOOK_TOKEN = os.environ.get("MOBILE_MONEY_WEBHOOK_TOKEN", "").strip()
MOBILE_MONEY_USSD = {
    "AIRTEL": os.environ.get("MOBILE_MONEY_USSD_AIRTEL", "*501#"),
    "ORANGE": os.environ.get("MOBILE_MONEY_USSD_ORANGE", "*144#"),
    "MPESA": os.environ.get("MOBILE_MONEY_USSD_MPESA", "*150#"),
}

# Sentry (optionnel)
SENTRY_DSN = os.environ.get("SENTRY_DSN", "").strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
            send_default_pii=False,
            environment="development" if DEBUG else "production",
        )
    except ImportError:
        pass

# Bird (WhatsApp : OTP + reçus de paiement). Clé dans BIRD_API_KEY, jamais dans le code.
BIRD_API_KEY = os.environ.get("BIRD_API_KEY", "").strip()
BIRD_FROM_EMAIL = os.environ.get("BIRD_FROM_EMAIL", "") or DEFAULT_FROM_EMAIL
BIRD_WHATSAPP_TEMPLATE = os.environ.get("BIRD_WHATSAPP_TEMPLATE", "bird_otp").strip() or "bird_otp"
BIRD_WHATSAPP_PAIEMENT_TEMPLATE = os.environ.get(
    "BIRD_WHATSAPP_PAIEMENT_TEMPLATE", "bird_delivery_update"
).strip() or "bird_delivery_update"
BIRD_WHATSAPP_LANGUAGE = os.environ.get("BIRD_WHATSAPP_LANGUAGE", "en").strip() or "en"

_EMAIL_CONSOLE = "django.core.mail.backends.console.EmailBackend"
_EMAIL_SMTP = "django.core.mail.backends.smtp.EmailBackend"
_EMAIL_BIRD = "ds.bird.BirdEmailBackend"
_email_env = os.environ.get("EMAIL_BACKEND", "")
if _email_env:
    EMAIL_BACKEND = _email_env
elif BIRD_API_KEY and not DEBUG:
    EMAIL_BACKEND = _EMAIL_BIRD
elif DEBUG:
    EMAIL_BACKEND = _EMAIL_CONSOLE
else:
    EMAIL_BACKEND = _EMAIL_SMTP
    if not EMAIL_HOST:
        raise ImproperlyConfigured(
            "EMAIL_HOST ou BIRD_API_KEY doit être défini en production."
        )
